name = "patriciabacelarpsicologia"
account_id = "b5cf8f7f56a6d1c6b260865d31f0a7b0"
workers_dev = true
compatibility_date = "2025-04-15"

# Coloque o caminho para o arquivo principal do Worker diretamente aqui
main = "./out/worker-site/index.js"

[build]
command = "npm run build"  # Comando para gerar a build

[site]
bucket = "./out"  # Diretório do site
