name = "patriciabacelarpsicologia"
account_id = "b5cf8f7f56a0d1c6b26086d31f0a7b0"
workers_dev = true
compatibility_date = "2025-04-15"

[build]
command = "npm run build && npm run export"
upload.dir = "out"  # Diretório onde os arquivos estáticos são gerados após o comando 'npm run export'

[site]
bucket = "./out"  # A pasta onde estão os arquivos exportados
entry-point = "."  # Aqui, o entry-point pode ser '.' (pasta raiz) para um site estático
